create database mystifly;

use mystifly;

create table airlines(
MyFareBoxRef varchar(30),
TotalFarePMINR int,
TPaxCount int,
Total_Revenue decimal,
TotalCosts decimal,
Calculated_Retention decimal,
ClientMCN varchar(30),
Client varchar(30),
Region varchar(30),
CabinClass varchar(30),
AirlineCode varchar(30),
OriginCountryCode varchar(30),
DestinationCountryCode varchar(30),
IsInternational varchar(30),
Segments varchar(30),
VendorGroup varchar(30),
OnD varchar(30));


set session sql_mode = '';

load data infile 
'D:/Assessment_exercise1.csv'
into table airlines
fields terminated by ','
enclosed by '"'
lines terminated by '\r\n'
ignore 1 rows;

select * from airlines;

#Q1
#Highest profit by which client
select client, sum(calculated_retention) from airlines group by client 
order by sum(calculated_retention) desc limit 0,10;

#Highest Fare by which client
select client, sum(totalfarepminr) from airlines group by client 
order by sum(totalfarepminr) desc limit 0,10;

#Highest revenue by which client
select client, sum(total_revenue) from airlines group by client 
order by sum(total_revenue) desc limit 0,10;

#Most customer given by which client (Popular client)
select client, sum(TPaxCount) from airlines group by client 
order by sum(TPaxCount) desc limit 0,10;
#We can include client A also because its providing highest no of customer and bookings + generating third largest proft after G & B
#We should go with Client B and G and on my recomendation we should go with client A Also
select client, count(myfareboxref) from airlines group by client order by count(myfareboxref) desc ;


#Top 3 vendors prioritise most - Q2
select vendorgroup , sum(calculated_retention), sum(totalfarepminr) from airlines group by vendorgroup 
order by sum(calculated_retention) desc limit 0,10;

select vendorgroup , sum(total_revenue), sum(totalfarepminr) from airlines group by vendorgroup 
order by sum(total_revenue) desc limit 0,10;


#Business potential - Q4
#Max. profit generated by which origin country
select OriginCountryCode, sum(calculated_retention) from airlines group by OriginCountryCode 
order by sum(calculated_retention) desc;

#Max. revenue generated by which origin country
select OriginCountryCode, sum(total_revenue) from airlines group by OriginCountryCode 
order by sum(total_revenue) desc;

#Max. profit generated by which region
select Region, sum(calculated_retention) from airlines group by Region 
order by sum(calculated_retention) desc;

#Max. revenue generated by which region
select Region, sum(total_revenue) from airlines group by Region 
order by sum(total_revenue) desc;

#Future business Potential
#Paid Highest fare by origin country
select OriginCountryCode, sum(TotalFarePMINR) from airlines group by OriginCountryCode 
order by sum(TotalFarePMINR) desc limit 0,10;
#Highest no of passengers origin country
select OriginCountryCode, sum(TPaxCount) from airlines group by OriginCountryCode 
order by sum(TPaxCount) desc limit 0,10;
#Highest number of booking from which origin
select origincountrycode, count(myfareboxref) from airlines group by OriginCountryCode 
order by count(myfareboxref) desc limit 0,10;


#Q3 These are best client- airline combination which we can sell more
select client, airlinecode, Calculated_Retention from airlines
order by Calculated_Retention desc limit 1,10;

#client and airline combination sum - top 10 will be the most profitable combination

select * from airlines group by MyFareBoxRef order by client;

#This is the best combination
select * from combinations order by profit desc limit 0,10 ;
select concat(client, ' - ', airlinecode) as combination_client_Airline , profit from combinations order by profit desc limit 0,10 ;

create view combinations as 
(select client, sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client a' group by airlinecode
union  
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client b' group by airlinecode
union
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client c' group by airlinecode
union  
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client d' group by airlinecode
union  
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client e' group by airlinecode 
union 
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client f' group by airlinecode
union  
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client g' group by airlinecode 
union 
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client h' group by airlinecode
union
select client,sum(Calculated_Retention) as profit, airlinecode from airlines where client = 'client i' group by airlinecode);







select max(Calculated_Retention) ;
select * from airlines  where Calculated_Retention = (select max(Calculated_Retention) from airlines) ;

select airlinecode, client, Calculated_Retention from airlines  
where Calculated_Retention = (select max(Calculated_Retention) from airlines);

select client, airlinecode, sum(Calculated_Retention) from airlines group by client and airlinecode
order by sum(Calculated_Retention);




select vendorgroup, avg(TotalFarePMINR) from airlines group by vendorgroup;
select * from airlines  where Calculated_Retention = (select max(Calculated_Retention) from airlines) ;

